packages:
  - packages/*

catalog:
  '@eslint/js': 9.36.0
  '@eslint/json': 0.13.2
  '@eslint/markdown': 7.3.0
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@microsoft/api-extractor-model': 7.30.7
  '@microsoft/tsdoc': 0.15.1
  eslint: 9.36.0
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  globals: 16.4.0
  prettier: 3.6.2
  tsdown: 0.14.2
  typescript-eslint: 8.44.1

onlyBuiltDependencies:
  - nx
